Fixed bugs, updated makefile

diff --git a/generatedCode/Makefile b/generatedCode/Makefile
--- a/generatedCode/Makefile
+++ b/generatedCode/Makefile
@@ -8,6 +8,17 @@ VPATH = .:${OCTAVEC}
 CC=gcc
 CFLAGS = -std=c99 -lm -lopenblas -lscalapack -lfftw3
 
+all_dirs := $(shell ls -d */)
+speed_dirs := $(shell ls -d SPEED*/)
+nonspeed_dirs := $(shell ls -d */ | grep '^[^SPEED].*')
+
+setup:
+	module load binutils; \
+	module load nodejs; \
+	module load GCC; \
+	module load ScaLAPACK/2.1.0-gompi-2020b; \
+	module load FFTW; \
+
 # Copy mfiles from tests_C_Octave folder into generatedCode and "clean"
 copyall:
 	if [ -f "matrix.o" ]; then \
@@ -23,40 +34,55 @@ copyall:
 		fi \
 	done; \
 	
-# Generate main.c for all mfiles that haven't already been generated	
+# Generate one C program
+# make genone ARGS=testname
+genone:
+	eval npx ts-node $$TS_TRAVERSAL/index.ts $(shell pwd)/$(ARGS)/$(ARGS).m $(shell pwd)/$(ARGS) $$TS_TRAVERSAL 0 0; \
+	
+# Generate main.c for all mfiles that haven't already been generated
+# eval npx ts-node $$TS_TRAVERSAL/index.ts $$fulldir/$$dir.m $$TEST $$TS_TRAVERSAL 0 0;
 genall:
-	mfiles=$$(find $$OCTAVEC/tests_C_Octave -type f -name "*.m"); \
-	for mfile in $$mfiles; do \
-		filename=$$(basename -- "$$mfile"); \
-		filename="$${filename%.*}"; \
-		if [ ! -f "$(shell pwd)/$$filename/main.c" ]; then \
-			echo $$filename; \
-			eval npx ts-node $$TS_TRAVERSAL/index.ts $(shell pwd)/$$filename/$$filename.m $$TEST $$TS_TRAVERSAL 0 0; \
+	for dir in $(all_dirs) ; do \
+		dir=$${dir//\//}; \
+		fulldir="$(shell pwd)/$$dir"; \
+		if [ ! -f "$$fulldir/main.c" ]; then \
+			echo $$dir; \
+			eval npx ts-node $$TS_TRAVERSAL/index.ts $$fulldir/$$dir.m $$fulldir $$TS_TRAVERSAL 0 0; \
 		fi \
 	done; \
-
+	
 # Generate main.c for all mfiles, regardless of whether already generated
 regenall:
-	mfiles=$$(find $(shell pwd) -type f -name "*.m"); \
-	for mfile in $$mfiles; do \
-		filename=$$(basename -- "$$mfile"); \
-		filename="$${filename%.*}"; \
-		echo $$filename; \
-		eval npx ts-node $$TS_TRAVERSAL/index.ts $(shell pwd)/$$filename/$$filename.m $$TEST $$TS_TRAVERSAL 0 0; \
-	done; \
-
-# Compile all C programs
-dirs := $(shell ls -d */)
-compileall: $(dirs)
-	good=(); \
-	bad=(); \
-	for dir in $(dirs) ; do \
+	for dir in $(all_dirs) ; do \
 		dir=$${dir//\//}; \
 		fulldir="$(shell pwd)/$$dir"; \
 		echo $$dir; \
-		mfiles=$$(find $$fulldir -type f -name "*.m"); \
+		eval npx ts-node $$TS_TRAVERSAL/index.ts $$fulldir/$$dir.m $$fulldir $$TS_TRAVERSAL 0 0; \
+	done; \
+
+
+# Compile all C programs
+# make compileall SPEED=1
+compileall:
+	dirs=$$(echo $(all_dirs)); \
+	if [[ "$(SPEED)" == "1" ]]; then \
+		echo "Compiling all nonspeed tests";\
+		dirs=$$(echo $(nonspeed_dirs)); \
+	elif [[ "$(SPEED)" == "2" ]]; then \
+		echo "Compiling all speed tests";\
+		dirs=$$(echo $(speed_dirs)); \
+	fi; \
+	good=(); \
+	bad=(); \
+	for dir in $$dirs; do \
+		dir=$${dir//\//}; \
+		fulldir="$(shell pwd)/$$dir"; \
+		echo $$dir; \
+		mfiles=$$(ls -d $$fulldir/* | grep -oP '^((?!_torun).)*\.m'); \
 		srcs=$$(echo "$$mfiles" | sed "s/$$dir\.m/main/"); \
+		srcs=$$(echo "$$srcs" | sed "s/\.m//"); \
 		objects=$$(echo "$$mfiles" | sed "s/$$dir\.m/main.o/"); \
+		objects=$$(echo "$$objects" | sed "s/\.m/.o/"); \
 		for src in $$srcs; do \
 			eval $(CC) -c -o $$src.o $$src.c $(CFLAGS) $(LIB) $(INC); \
 		done; \
@@ -77,13 +103,16 @@ compileall: $(dirs)
 	echo -e $${good[@]} >> compile_log.txt; \
 	echo -e "\nERROR" >> compile_log.txt; \
 	echo -e $${bad[@]} >> compile_log.txt; \
+	
 # Compile one C program
 # make compileone ARGS=testname
 compileone:
 	fulldir="$(shell pwd)/$(ARGS)"; \
-	mfiles=$$(find $$fulldir -type f -name "*.m"); \
+	mfiles=$$(ls -d $$fulldir/* | grep -oP '^((?!_torun).)*\.m'); \
 	srcs=$$(echo "$$mfiles" | sed "s/$(ARGS)\.m/main/"); \
+	srcs=$$(echo "$$srcs" | sed "s/\.m//"); \
 	objects=$$(echo "$$mfiles" | sed "s/$(ARGS)\.m/main.o/"); \
+	objects=$$(echo "$$objects" | sed "s/\.m/.o/"); \
 	for src in $$srcs; do \
 		eval $(CC) -c -o $$src.o $$src.c $(CFLAGS) $(LIB) $(INC); \
 	done; \
@@ -97,24 +126,35 @@ compileone:
 	
 # Show MATLAB output for all mfiles
 runmatlab:
+	module load MATLAB/2021a; \
 	mfiles=$$(find $(shell pwd) -type f -name "*.m"); \
 	for mfile in $$mfiles; do \
 		filename=$$(basename -- "$$mfile"); \
 		echo $$filename; \
 		matlab -nojvm -nodisplay -nosplash < $$mfile; \
 	done; \
+	module unload MATLAB/2021a; \
 	
 # Compare outputs of generated C program and original mfile for all tests
+# add argument to ignore speed tests
 compareall:
+	module load MATLAB/2021a; \
+	dirs=$$(echo $(all_dirs)); \
+	if [[ "$(SPEED)" == "1" ]]; then \
+		echo "Comparing all nonspeed tests";\
+		dirs=$$(echo $(nonspeed_dirs)); \
+	elif [[ "$(SPEED)" == "2" ]]; then \
+		echo "Comparing all speed tests";\
+		dirs=$$(echo $(speed_dirs)); \
+	fi; \
 	good=(); \
 	bad=(); \
-	mfiles=$$(find $(shell pwd) -type f -name "*.m"); \
-	for mfile in $$mfiles; do \
-		filename=$$(basename -- "$$mfile"); \
-		filename="$${filename%.*}"; \
-		fulldir="$(shell pwd)/$$filename"; \
-		(timeout 5 $$fulldir/test 2>/dev/null | \
-			sed -z 's/-nan/inf/gi' | sed -z 's/nan/inf/gi' | \
+	for dir in $$dirs; do \
+		dir=$${dir//\//}; \
+		fulldir="$(shell pwd)/$$dir"; \
+		echo $$dir; \
+		(timeout 120 $$fulldir/test 2>/dev/null | \
+			sed -z 's/-nan/inf/gi' | sed -z 's/nan/inf/gi' | sed -z 's/inf +infi/inf/gi' | \
 			sed -z 's/\.000000//g' | sed -z 's/\.00000//g' | sed -z 's/\.0000//g' | \
 			tr -s ' \t\n' | sed -z 's/\n/ \n/g' | \
 			sed -z -E 's/-\s*(0+(\.0+)?(-|\+|\s))/\1/g' | sed -z -E 's/-\s*(0+(\.0+)?i)/+\1/g' | \
@@ -123,8 +163,9 @@ compareall:
 			sed -z -E 's/(\.[[:digit:]]+)0+(\-|\+|i|\s|\n)/\1\2/g' | \
 			sed -z -E 's/(\.[[:digit:]]+)0+(\-|\+|i|\s|\n)/\1\2/g' | \
 			sed -z -E 's/(\.[[:digit:]]+)0+(\-|\+|i|\s|\n)/\1\2/g') > $$fulldir/f1; \
-		(timeout 5 matlab -nodisplay -nosplash < $$fulldir/$$filename.m 2>/dev/null | \
+		(timeout 120 matlab -nodisplay -nosplash < $$fulldir/$${dir}_torun.m 2>/dev/null | \
 			tail -n+10 | sed -z 's/>>//gi' | \
+			sed -E "s/\"@(-?[0-9]+(\.[0-9]+)?( [+-] ?[0-9]+(\.[0-9]+)?i)?)\"/\1/g" | \
 			sed -z 's/-nan/inf/gi' | sed -z 's/nan/inf/gi' | \
 			sed -z 's/\.000000//g' | sed -z 's/\.00000//g' | sed -z 's/\.0000//g' | \
 			tr -s ' \t\n' | sed -z 's/\n/ \n/g' | \
@@ -134,10 +175,16 @@ compareall:
 			sed -z -E 's/(\.[[:digit:]]+)0+(\-|\+|i|\s|\n)/\1\2/g' | \
 			sed -z -E 's/(\.[[:digit:]]+)0+(\-|\+|i|\s|\n)/\1\2/g' | \
 			sed -z -E 's/(\.[[:digit:]]+)0+(\-|\+|i|\s|\n)/\1\2/g' | \
-			sed -z 's/\n\s/\n/gi' | sed -z 's/  \n//gi') > $$fulldir/f2; \
-		timeout 5 diff -wi $$fulldir/f1 $$fulldir/f2 && \
-			(echo -e "\e[1;32mSUCCESS\e[0m : $$filename" && good+="$$filename\n")||\
-			(echo -e "\e[1;31mDIFF ERROR\e[0m : $$filename" && bad+="$$filename\n");\
+			sed -z 's/\n\s/\n/gi' | grep "\S") > $$fulldir/f2; \
+		timeout 120 diff -wi $$fulldir/f1 $$fulldir/f2; \
+		RESULT=$$?; \
+		if [[ "$$RESULT" == "0" ]]; then \
+			echo -e "\e[1;32mSUCCESS\e[0m : $$dir";\
+			good+="$$dir\n"; \
+		else \
+			echo -e "\e[1;31mDIFF ERROR\e[0m : $$dir";\
+			bad+="$$dir\n";\
+		fi; \
 		rm $$fulldir/f1; \
 		rm $$fulldir/f2; \
 	done; \
@@ -145,13 +192,16 @@ compareall:
 	echo -e $${good[@]} >> compare_log.txt; \
 	echo -e "\nERROR" >> compare_log.txt; \
 	echo -e $${bad[@]} >> compare_log.txt; \
+	module unload MATLAB/2021a; \
+	
 	
 # Compare outputs of generated C program and original mfile for one test
 # make compareone ARGS=testname
 compareone:
+	module load MATLAB/2021a; \
 	fulldir="$(shell pwd)/$(ARGS)"; \
 	($$fulldir/test 2>/dev/null | \
-		sed -z 's/-nan/inf/gi' | sed -z 's/nan/inf/gi' | \
+		sed -z 's/-nan/inf/gi' | sed -z 's/nan/inf/gi' | sed -z 's/inf +infi/inf/gi' | \
 		sed -z 's/\.000000//g' | sed -z 's/\.00000//g' | sed -z 's/\.0000//g' | \
 		tr -s ' \t\n' | sed -z 's/\n/ \n/g' | \
 		sed -z -E 's/-\s*(0+(\.0+)?(-|\+|\s))/\1/g' | sed -z -E 's/-\s*(0+(\.0+)?i)/+\1/g' | \
@@ -160,8 +210,10 @@ compareone:
 		sed -z -E 's/(\.[[:digit:]]+)0+(\-|\+|i|\s|\n)/\1\2/g' | \
 		sed -z -E 's/(\.[[:digit:]]+)0+(\-|\+|i|\s|\n)/\1\2/g' | \
 		sed -z -E 's/(\.[[:digit:]]+)0+(\-|\+|i|\s|\n)/\1\2/g') > $$fulldir/f1; \
-	(matlab -nodisplay -nosplash < $$fulldir/$(ARGS).m 2>/dev/null | \
+	(matlab -nodisplay -nosplash < $$fulldir/$(ARGS)_torun.m 2>/dev/null | \
 		tail -n+10 | sed -z 's/>>//gi' | \
+		sed -E "s/\"@(-?[0-9]+(\.[0-9]+)?( [+-] ?[0-9]+(\.[0-9]+)?i)?)\"/\1/g" | \
+		sed -E "s/\"@Inf\"/inf/g" | \
 		sed -z 's/-nan/inf/gi' | sed -z 's/nan/inf/gi' | \
 		sed -z 's/\.000000//g' | sed -z 's/\.00000//g' | sed -z 's/\.0000//g' | \
 		tr -s ' \t\n' | sed -z 's/\n/ \n/g' | \
@@ -171,7 +223,132 @@ compareone:
 		sed -z -E 's/(\.[[:digit:]]+)0+(\-|\+|i|\s|\n)/\1\2/g' | \
 		sed -z -E 's/(\.[[:digit:]]+)0+(\-|\+|i|\s|\n)/\1\2/g' | \
 		sed -z -E 's/(\.[[:digit:]]+)0+(\-|\+|i|\s|\n)/\1\2/g' | \
-		sed -z 's/\n\s/\n/gi' | sed -z 's/  \n//gi') > $$fulldir/f2; \
+		sed -z 's/\n\s/\n/gi' | grep "\S") > $$fulldir/f2; \
 	diff -wi $$fulldir/f1 $$fulldir/f2 && \
 		echo -e "\e[1;32mSUCCESS\e[0m : $(ARGS)"||\
 		echo -e "\e[1;31mDIFF ERROR\e[0m : $(ARGS)";\
+	module unload MATLAB/2021a; \
+	
+
+# OLD STUFF
+
+# For testing
+testing:
+	for dir in $(all_dirs) ; do \
+		dir=$${dir//\//}; \
+		fulldir="$(shell pwd)/$$dir"; \
+		mfiles=$$(ls $$fulldir | grep -oP '^((?!_torun).)*\.m'); \
+		mfiles2=$$(ls -d $$fulldir/* | grep -oP '^((?!_torun).)*\.m'); \
+		mfiles3=$$(find $$fulldir -type f -name "*.m"); \
+		echo $$mfiles2; \
+	done; \
+
+# Compare outputs of generated C program and original mfile for all tests
+# add argument to ignore speed tests
+compareall2:
+	module load MATLAB/2021a; \
+	dirs=$$(echo $(all_dirs)); \
+	if [[ "$(SPEED)" == "1" ]]; then \
+		echo "Comparing all nonspeed tests";\
+		dirs=$$(echo $(nonspeed_dirs)); \
+	elif [[ "$(SPEED)" == "2" ]]; then \
+		echo "Comparing all speed tests";\
+		dirs=$$(echo $(speed_dirs)); \
+	fi; \
+	good=(); \
+	bad=(); \
+	for dir in $$dirs; do \
+		dir=$${dir//\//}; \
+		fulldir="$(shell pwd)/$$dir"; \
+		echo $$dir; \
+		(timeout 120 $$fulldir/test 2>/dev/null | \
+			sed -z 's/-nan/inf/gi' | sed -z 's/nan/inf/gi' | sed -z 's/inf +infi/inf/gi' | \
+			sed -z 's/\.000000//g' | sed -z 's/\.00000//g' | sed -z 's/\.0000//g' | \
+			tr -s ' \t\n' | sed -z 's/\n/ \n/g' | \
+			sed -z -E 's/-\s*(0+(\.0+)?(-|\+|\s))/\1/g' | sed -z -E 's/-\s*(0+(\.0+)?i)/+\1/g' | \
+			sed -z -E 's/(\.[[:digit:]]+)0+(\-|\+|i|\s|\n)/\1\2/g' | \
+			sed -z -E 's/(\.[[:digit:]]+)0+(\-|\+|i|\s|\n)/\1\2/g' | \
+			sed -z -E 's/(\.[[:digit:]]+)0+(\-|\+|i|\s|\n)/\1\2/g' | \
+			sed -z -E 's/(\.[[:digit:]]+)0+(\-|\+|i|\s|\n)/\1\2/g' | \
+			sed -z -E 's/(\.[[:digit:]]+)0+(\-|\+|i|\s|\n)/\1\2/g') > $$fulldir/f1; \
+		(timeout 120 matlab -nodisplay -nosplash < $$fulldir/$${dir}_torun.m 2>/dev/null | \
+			tail -n+10 | sed -z 's/>>//gi' | \
+			sed -E "s/\"@(-?[0-9]+(\.[0-9]+)?( [+-] ?[0-9]+(\.[0-9]+)?i)?)\"/\1/g" | \
+			sed -z 's/-nan/inf/gi' | sed -z 's/nan/inf/gi' | \
+			sed -z 's/\.000000//g' | sed -z 's/\.00000//g' | sed -z 's/\.0000//g' | \
+			tr -s ' \t\n' | sed -z 's/\n/ \n/g' | \
+			sed -z -E 's/-\s*(0+(\.0+)?(-|\+|\s))/\1/g' | sed -z -E 's/-\s*(0+(\.0+)?i)/+\1/g' | \
+			sed -z -E 's/(\.[[:digit:]]+)0+(\-|\+|i|\s|\n)/\1\2/g' | \
+			sed -z -E 's/(\.[[:digit:]]+)0+(\-|\+|i|\s|\n)/\1\2/g' | \
+			sed -z -E 's/(\.[[:digit:]]+)0+(\-|\+|i|\s|\n)/\1\2/g' | \
+			sed -z -E 's/(\.[[:digit:]]+)0+(\-|\+|i|\s|\n)/\1\2/g' | \
+			sed -z -E 's/(\.[[:digit:]]+)0+(\-|\+|i|\s|\n)/\1\2/g' | \
+			sed -z 's/\n\s/\n/gi' | grep "\S") > $$fulldir/f2; \
+		timeout 120 diff -wi $$fulldir/f1 $$fulldir/f2 && \
+			(echo -e "\e[1;32mSUCCESS\e[0m : $$dir" && good+="$$dir\n")||\
+			(echo -e "\e[1;31mDIFF ERROR\e[0m : $$dir" && bad+="$$dir\n");\
+		rm $$fulldir/f1; \
+		rm $$fulldir/f2; \
+	done; \
+	echo -e "SUCCESS" > compare_log.txt; \
+	echo -e $${good[@]} >> compare_log.txt; \
+	echo -e "\nERROR" >> compare_log.txt; \
+	echo -e $${bad[@]} >> compare_log.txt; \
+	module unload MATLAB/2021a; \
+	
+# Compare outputs of generated C program and original mfile for all tests
+# add argument to ignore speed tests
+compareall3:
+	module load MATLAB/2021a; \
+	dirs=$$(echo $(all_dirs)); \
+	if [[ "$(SPEED)" == "1" ]]; then \
+		echo "Comparing all nonspeed tests";\
+		dirs=$$(echo $(nonspeed_dirs)); \
+	elif [[ "$(SPEED)" == "2" ]]; then \
+		echo "Comparing all speed tests";\
+		dirs=$$(echo $(speed_dirs)); \
+	fi; \
+	good=(); \
+	bad=(); \
+	for dir in $$dirs; do \
+		dir=$${dir//\//}; \
+		fulldir="$(shell pwd)/$$dir"; \
+		echo $$dir; \
+		(timeout 120 $$fulldir/test 2>/dev/null | \
+			sed -z 's/-nan/inf/gi' | sed -z 's/nan/inf/gi' | sed -z 's/inf +infi/inf/gi' | \
+			sed -z 's/\.000000//g' | sed -z 's/\.00000//g' | sed -z 's/\.0000//g' | \
+			tr -s ' \t\n' | sed -z 's/\n/ \n/g' | \
+			sed -z -E 's/-\s*(0+(\.0+)?(-|\+|\s))/\1/g' | sed -z -E 's/-\s*(0+(\.0+)?i)/+\1/g' | \
+			sed -z -E 's/(\.[[:digit:]]+)0+(\-|\+|i|\s|\n)/\1\2/g' | \
+			sed -z -E 's/(\.[[:digit:]]+)0+(\-|\+|i|\s|\n)/\1\2/g' | \
+			sed -z -E 's/(\.[[:digit:]]+)0+(\-|\+|i|\s|\n)/\1\2/g' | \
+			sed -z -E 's/(\.[[:digit:]]+)0+(\-|\+|i|\s|\n)/\1\2/g' | \
+			sed -z -E 's/(\.[[:digit:]]+)0+(\-|\+|i|\s|\n)/\1\2/g') > $$fulldir/f1; \
+		(timeout 120 matlab -nodisplay -nosplash < $$fulldir/$${dir}_torun.m 2>/dev/null | \
+			tail -n+10 | sed -z 's/>>//gi' | \
+			sed -E "s/\"@(-?[0-9]+(\.[0-9]+)?( [+-] ?[0-9]+(\.[0-9]+)?i)?)\"/\1/g" | \
+			sed -z 's/-nan/inf/gi' | sed -z 's/nan/inf/gi' | \
+			sed -z 's/\.000000//g' | sed -z 's/\.00000//g' | sed -z 's/\.0000//g' | \
+			tr -s ' \t\n' | sed -z 's/\n/ \n/g' | \
+			sed -z -E 's/-\s*(0+(\.0+)?(-|\+|\s))/\1/g' | sed -z -E 's/-\s*(0+(\.0+)?i)/+\1/g' | \
+			sed -z -E 's/(\.[[:digit:]]+)0+(\-|\+|i|\s|\n)/\1\2/g' | \
+			sed -z -E 's/(\.[[:digit:]]+)0+(\-|\+|i|\s|\n)/\1\2/g' | \
+			sed -z -E 's/(\.[[:digit:]]+)0+(\-|\+|i|\s|\n)/\1\2/g' | \
+			sed -z -E 's/(\.[[:digit:]]+)0+(\-|\+|i|\s|\n)/\1\2/g' | \
+			sed -z -E 's/(\.[[:digit:]]+)0+(\-|\+|i|\s|\n)/\1\2/g' | \
+			sed -z 's/\n\s/\n/gi' | grep "\S") > $$fulldir/f2; \
+		if $$(timeout 120 diff -wi $$fulldir/f1 $$fulldir/f2); then \
+			echo -e "\e[1;32mSUCCESS\e[0m : $$dir";\
+			good+="$$dir\n"; \
+		else \
+			echo -e "\e[1;31mDIFF ERROR\e[0m : $$dir";\
+			bad+="$$dir\n";\
+		fi; \
+		rm $$fulldir/f1; \
+		rm $$fulldir/f2; \
+	done; \
+	echo -e "SUCCESS" > compare_log.txt; \
+	echo -e $${good[@]} >> compare_log.txt; \
+	echo -e "\nERROR" >> compare_log.txt; \
+	echo -e $${bad[@]} >> compare_log.txt; \
+	module unload MATLAB/2021a; \
